### PR TITLE
Replaced testcontainers with Debezium Kafka cluster

### PR DESCRIPTION
**Pull request by hekonsek**
Hi,

Can you consider using Debezium KafkaCluster instead of Kafka Docker images? That would speed up and simplify build a little bit. Right now test Docker-based tests requires some predefined configuration file for Kafka:

```
[ERROR] me.escoffier.fluid.kafka.KafkaSourceTest  Time elapsed: 0.819 s  <<< ERROR!
java.lang.ExceptionInInitializerError
	at me.escoffier.fluid.kafka.KafkaSourceTest.<clinit>(KafkaSourceTest.java:33)
Caused by: java.io.IOException: Invalid Auth config file
	at me.escoffier.fluid.kafka.KafkaSourceTest.<clinit>(KafkaSourceTest.java:33)
``` 

Thanks!

### CODE REVIEW

**Comment by cescoffier** [comment]
Interesting, it's what I was using before, but it didn't work anymore for me. Let me try your settings.

**Comment by hekonsek** [comment]
Works on my machine :P 

If it still doesn't work for you, can you let me know what error do you see? Maybe I could help.

**Comment by cescoffier** [comment]
I see a timeout:

```
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server 'localhost:2181' with timeout of 6000 ms
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1233)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:157)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:131)
	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:103)
	at kafka.utils.ZkUtils$.apply(ZkUtils.scala:85)
	at kafka.server.KafkaServer.initZk(KafkaServer.scala:341)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:191)
	at io.debezium.kafka.KafkaServer.startup(KafkaServer.java:207)
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
	at io.debezium.kafka.KafkaCluster.startup(KafkaCluster.java:229)
	at me.escoffier.fluid.kafka.KafkaSourceTest.beforeClass(KafkaSourceTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
```

I've tried to configure the zookeepet timeout without success.

**Comment by hekonsek** [comment]
This setup works for my laptop and Travis CI. It is also used in vertx-client-kafka tests and some of our other projects that I would assume that you have firewall issue or other process conflict. :(

**Comment by cescoffier** [comment]
Unfortunately, no conflict or firewall. Let me look a bit deeper.

**Comment by cescoffier** [comment]
Making progress!

**Comment by cescoffier** [comment]
I've found the way to increase the timeout. I've also changed the location of the directory.

**Comment by hekonsek** [comment]
Hmmm, this is still quite a mystery to me why you hit a timeout at all. I bet you're not running machine slow enough to wait 5 seconds for embedded ZooKeeper server to start :) .

But anyway - it is good that we have it merged! Many thanks, Clement!

**Comment by cescoffier** [comment]
If you want the full story, it worked perfectly well before I update my
OS....

**Pull request merged**
